### ISSUE TITLE
Separate blockly core into a shared library across BTs, PDDL and FSMs

### ISSUE THREAD

**Issue by Flamak** [AI-Planning/blockly-pddl#26]
![image](https://user-images.githubusercontent.com/7831734/185157737-0c83e00d-c834-451d-9919-cde436d8c83d.png)

**Comment by aganil** [comment]
@eng-r, new branch, develop, has the new shared components under lib/. "Apps" under src/ have links to the shared components. Tested working for src/pddl/

**Comment by Flamak** [comment]
@aganil, are we ready to merge the related branch one?

**Comment by aganil** [comment]
Completed with PR #38
